cmake_minimum_required(VERSION 3.60)

project(
	TypeCounter
	VERSION 0.1.1
	DESCRIPTION "Application use to collect user type"
	LANGUAGES CXX C
)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${CMAKE_SOURCE_DIR}/out/bin")

add_subdirectory("${CMAKE_SOURCE_DIR}/src")